name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Fetch and process JSON files
        run: |
          mkdir -p data/novels
          BASE_URL="https://raw.githubusercontent.com/YuushaExa/novels-end/refs/heads/main/result/"
          
          for i in {1..100}; do
            URL="${BASE_URL}${i}.json.gz"
            OUTPUT_FILE="data/novels/${i}.json"
            
            # Download the gzipped file
            if curl -s -f -L "$URL" | gunzip -c > "$OUTPUT_FILE.tmp"; then
              # Validate JSON and only keep if valid
              if jq empty "$OUTPUT_FILE.tmp" 2>/dev/null; then
                mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"
                echo "Processed file $i.json successfully"
              else
                echo "Invalid JSON in file $i, skipping"
                rm -f "$OUTPUT_FILE.tmp"
                break
              fi
            else
              echo "Failed to fetch file $i, stopping"
              break
            fi
          done
      
      - name: Build Hugo
        run: hugo --minify --templateMetrics --templateMetricsHints --baseURL "https://yuushaexa.github.io/"
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
