name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq
          echo "Dependencies installed"
      
      - name: Fetch and decompress JSON files
        run: |
          echo "Creating data directory..."
          mkdir -p data/gzipped
          
          echo "Downloading tad1-data.json..."
          wget -q "https://raw.githubusercontent.com/YuushaExa/novels-all/refs/heads/main/result/tad1-data.json" -O tad1-data.json
          
          echo "Extracting IDs..."
          ids=$(jq -r '.[].id' tad1-data.json)
          echo "Found IDs: $(echo $ids | wc -w)"
          
          baseURL="https://raw.githubusercontent.com/YuushaExa/novels-end/refs/heads/main/result/"
          success=0
          failures=0
          
          for id in $ids; do
            output_file="data/gzipped/${id}.json.gz"
            echo "Downloading ${id}.json.gz..."
            
            if wget -q "${baseURL}${id}.json.gz" -O "$output_file"; then
              echo "Successfully downloaded ${id}.json.gz"
              if gzip -df "$output_file"; then
                ((success++))
                echo "Successfully decompressed ${id}.json.gz"
              else
                ((failures++))
                echo "Failed to decompress ${id}.json.gz"
                rm -f "$output_file"  # Clean up corrupted gzip
              fi
            else
              ((failures++))
              echo "Failed to download ${id}.json.gz"
            fi
          done
          
          echo "Download summary:"
          echo "Successfully processed: $success files"
          echo "Failed to process: $failures files"
          
          echo "Verifying downloaded files..."
          ls -lh data/gzipped/
          echo "Total JSON files: $(find data/gzipped/ -name "*.json" | wc -l)"
      
      - name: Build Hugo site
        run: |
          echo "Building Hugo site..."
          hugo --minify --baseURL "https://yuushaexa.github.io/"
          echo "Build complete"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
