name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'subforums/**'  # Only trigger if changes are in the `subforums` folder

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to compare changes between commits

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run SSG script
        run: node ssg.js  # The script will handle ISR logic internally

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Path to the generated static files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
