name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ssg script
        run: node ssg.js

      - name: Create tar.gz archive
        run: |
          mkdir -p public
          tar -czf public/site.tar.gz -C public .  # Bundle and compress all files

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/site.tar.gz  # Path to the .tar.gz file

      - name: Download and extract artifact
        run: |
          mkdir -p github-pages-deploy
          tar -xzf public/site.tar.gz -C github-pages-deploy  # Extract the .tar.gz file

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: github-pages-deploy
